#ifndef CST
#define CST

enum {NOMBRE_VILLE, TAILLE_POP_INIT, CHOIX_OP_SELECT, CHOIX_OP_REMPLACE, CHOIX_MOD_CROISE, REINIT, 
  OPTIONS_AVANCEES, DEMARAGE_ALGO};
  
#define LARGEUR_FENETRE  	400
#define LONGUEUR_FENETRE	300

#define LARGEUR_CARTE  	200
#define LONGUEUR_CARTE	250
  
#endif