#ifndef CST
#define CST

enum {ELITISME, ROULETTE, SELECT_RANG, TOURNOI};
enum {CROISEMENT_COMPLEXE,CROISEMENT_SIMPLE};
enum {REPLACE_ELIT,REPLACE_STAT};
enum {MODE_NBR_IT, MODE_TEMPS};
  
#define LARGEUR_FENETRE  	800
#define LONGUEUR_FENETRE	500

#define LARGEUR_CARTE  	200
#define LONGUEUR_CARTE	250
  
#endif
